[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc = "0.8.20"
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']

[lint]
exclude_lints = ["screaming-snake-case-const"]

[lint]
exclude_lints = ["screaming-snake-case-const"]
